module.exports = {
  root: true,
  env: {
    browser: true,
    es2022: true,
    node: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:vue/vue3-recommended',
    'prettier',
  ],
  parser: 'vue-eslint-parser',
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
    parser: '@typescript-eslint/parser',
  },
  plugins: ['@typescript-eslint'],
  rules: {
    'vue/multi-word-component-names': 'off',
    '@typescript-eslint/no-explicit-any': 'warn',
    '@typescript-eslint/no-non-null-assertion': 'warn',
    '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    'vue/no-v-html': 'warn',
    'vue/require-default-prop': 'off',
    'vue/no-setup-props-destructure': 'warn',
  },
  globals: {
    h: 'readonly',
    resolveComponent: 'readonly',
    computed: 'readonly',
    ref: 'readonly',
    reactive: 'readonly',
    watch: 'readonly',
    watchEffect: 'readonly',
    inject: 'readonly',
    provide: 'readonly',
    defineProps: 'readonly',
    defineEmits: 'readonly',
    defineExpose: 'readonly',
    withDefaults: 'readonly',
    onMounted: 'readonly',
    onUnmounted: 'readonly',
    onUpdated: 'readonly',
    nextTick: 'readonly',
    useSlots: 'readonly',
    useAttrs: 'readonly',
    useCSSModule: 'readonly',
    Transition: 'readonly',
    TransitionGroup: 'readonly',
    Teleport: 'readonly',
    KeepAlive: 'readonly',
    Suspense: 'readonly',
    defineAsyncComponent: 'readonly',
    shallowRef: 'readonly',
    shallowReactive: 'readonly',
    toRef: 'readonly',
    toRefs: 'readonly',
    readonly: 'readonly',
    unref: 'readonly',
    isRef: 'readonly',
  },
};
